/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Direction A — Material Design token palette
        'primary':                    '#3755c3',
        'primary-dim':                '#2848b7',
        'primary-fixed':              '#dde1ff',
        'primary-fixed-dim':          '#cad2ff',
        'on-primary':                 '#f8f7ff',
        'on-primary-fixed':           '#0732a3',
        'on-primary-fixed-variant':   '#3352c0',
        'on-primary-container':       '#2747b6',
        'primary-container':          '#dde1ff',
        'inverse-primary':            '#6d89fa',
        'secondary':                  '#5f5e62',
        'secondary-dim':              '#535356',
        'secondary-fixed':            '#e4e1e6',
        'secondary-fixed-dim':        '#d6d3d8',
        'on-secondary':               '#fbf8fc',
        'on-secondary-fixed':         '#3f3f43',
        'on-secondary-fixed-variant': '#5c5b5f',
        'on-secondary-container':     '#525155',
        'secondary-container':        '#e4e1e6',
        'tertiary':                   '#635b77',
        'tertiary-dim':               '#574f6a',
        'tertiary-fixed':             '#e9ddff',
        'tertiary-fixed-dim':         '#dbcff0',
        'on-tertiary':                '#fdf7ff',
        'on-tertiary-fixed':          '#433b55',
        'on-tertiary-fixed-variant':  '#605773',
        'on-tertiary-container':      '#564d69',
        'tertiary-container':         '#e9ddff',
        'surface':                    '#faf8ff',
        'surface-bright':             '#faf8ff',
        'surface-dim':                '#cdd9ff',
        'surface-tint':               '#3755c3',
        'surface-variant':            '#d9e2ff',
        'surface-container-lowest':   '#ffffff',
        'surface-container-low':      '#f2f3ff',
        'surface-container':          '#eaedff',
        'surface-container-high':     '#e2e7ff',
        'surface-container-highest':  '#d9e2ff',
        'on-surface':                 '#113069',
        'on-surface-variant':         '#445d99',
        'inverse-surface':            '#060e20',
        'inverse-on-surface':         '#959cb5',
        'background':                 '#faf8ff',
        'on-background':              '#113069',
        'outline':                    '#6079b7',
        'outline-variant':            '#98b1f2',
        'error':                      '#9e3f4e',
        'error-dim':                  '#4f0116',
        'error-container':            '#ff8b9a',
        'on-error':                   '#fff7f7',
        'on-error-container':         '#782232',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
        full:    '0.75rem',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body:     ['Manrope', 'sans-serif'],
        label:    ['Manrope', 'sans-serif'],
        sans:     ['Manrope', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
